<?php
namespace frontend\components;

use yii\base\Widget;
use yii\helpers\Html;

class HelloWidget extends Widget
{
    public $message;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if($this->message == null)
        {
            $this->message = "Hello world";
        }
    }

    public function run()
    {
        return Html::encode($this->message);
    }
}